server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://myFirstDataBase:W5gxHPeuMeffBvy9@cluster0.jh5wppb.mongodb.net/?retryWrites=true&w=majority}
      auto-index-creation: true


